apiVersion: v1
baseDomain: example.com
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 2
controlPlane: 
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
   - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: |
  {"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3Jub3VzaGkxZXJ4cGp6c2sxa2psbWNxZXRyamd5Z3pqdmU6SzJKV0FQQ1hSUUZaUTJXTk5EWlFKUkdCMDFZSzA1WDFYNDZTSlVYTVBTVjg2RDRPWlFKQUJLMkFSSFZTTk9aVw==","email":"rnoushi@edc4it.com"},"nexus-registry-int.apps.tools-na.prod.nextcle.com":{"auth":"cmVndXNlcjpJbnN0YWxsTTM=","email":"nobody@example.com"},"registry.connect.redhat.com":{"auth":"NzM1NjgxNHx1aGMtMUVSWFBqenNLMUtKTE1jUUV0ckpnWUdaSlZlOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJMFpqSmtZakZqWmpsaE1tWTBObU0xWW1Zd01XUm1NakptTnpZMlltRXlNeUo5LnNDMWVrSUNBclFDNFBKUllHS2VsT3hoaEs4VThCYk5oVE9lNUdORFpQTUdHX24tZ19ReVhnSVhOTEU5bXJxNldzY0dzNkk5UDlWN2NIUUgzLTVlMWlROGdJcXVsb0h2dUxiV05UWl9BNWZQQnpZTWF6TGR0Nmlhbkd3dk9ISm9XWHZyQmlMOW4tZ0xjNlVnSVVBb1NleGt6VkVsb093amhVcnpPQl9WbThvY25UaGZMWk41YkhiRFVKXzdLa0E1S09xc0pRRUdpVmZ5SWZ1a3BNQnlvcEJTamtPeFlmMEgwRzJaby0tWXVnamE0Y2J6N1RMWnNxenE3QkpFOG1FZGlTUFJaY1ppdTFFVmZicUZFanZRbkp3enNoRUtXamFKMnp4RGFTUjcteHdfTXJNOVhvVG1HMG9jMDIwWDk4Z2c0MHhMbXhtb2xBNHJxRTVOTHByTGRzb3JkdE11RVRXUU1HcnhQUnRNZ2d5c1FvU2lJSkhhQ053UkRZTmNEMjlYckppRG5KTGFpRVJXZThCMnRWdmZIOGlyUWFyNlEtRG01NXotaDkydS1ZZUhyU1ZWSzhNVGVBSFBWWlhLY1lqc0ZwMUFvWXdKQnh5eUhEdEFBR0Rrd3RWU1dpamptVVpSUlY5NF9wU05ERTJadmVuUTFJM2dSRHpFVEJmSEI4OFY3aVdfWlV2c1h3T0RNUGdnY1RIclQxWklocmFVSzUxb2xzNk82cG8tbmdiOE1TSGdYMHVTbDJEb0Q0cG1qTzVNZGRyU29pbEZJYUdGbFAzQTFYbWJ4bXN6NTZHYnlHUVgzdkt6S1VGSlJBTEF2Q0pwVWZNOGFKbEQ2V2ZEd1FHUTBSc0pQYk5EM2dVUlVZZEZPLXBaV2phLUNkb1kzcHFlR0tzNHBaTDVGY29N","email":"rnoushi@edc4it.com"},"registry.redhat.io":{"auth":"NzM1NjgxNHx1aGMtMUVSWFBqenNLMUtKTE1jUUV0ckpnWUdaSlZlOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJMFpqSmtZakZqWmpsaE1tWTBObU0xWW1Zd01XUm1NakptTnpZMlltRXlNeUo5LnNDMWVrSUNBclFDNFBKUllHS2VsT3hoaEs4VThCYk5oVE9lNUdORFpQTUdHX24tZ19ReVhnSVhOTEU5bXJxNldzY0dzNkk5UDlWN2NIUUgzLTVlMWlROGdJcXVsb0h2dUxiV05UWl9BNWZQQnpZTWF6TGR0Nmlhbkd3dk9ISm9XWHZyQmlMOW4tZ0xjNlVnSVVBb1NleGt6VkVsb093amhVcnpPQl9WbThvY25UaGZMWk41YkhiRFVKXzdLa0E1S09xc0pRRUdpVmZ5SWZ1a3BNQnlvcEJTamtPeFlmMEgwRzJaby0tWXVnamE0Y2J6N1RMWnNxenE3QkpFOG1FZGlTUFJaY1ppdTFFVmZicUZFanZRbkp3enNoRUtXamFKMnp4RGFTUjcteHdfTXJNOVhvVG1HMG9jMDIwWDk4Z2c0MHhMbXhtb2xBNHJxRTVOTHByTGRzb3JkdE11RVRXUU1HcnhQUnRNZ2d5c1FvU2lJSkhhQ053UkRZTmNEMjlYckppRG5KTGFpRVJXZThCMnRWdmZIOGlyUWFyNlEtRG01NXotaDkydS1ZZUhyU1ZWSzhNVGVBSFBWWlhLY1lqc0ZwMUFvWXdKQnh5eUhEdEFBR0Rrd3RWU1dpamptVVpSUlY5NF9wU05ERTJadmVuUTFJM2dSRHpFVEJmSEI4OFY3aVdfWlV2c1h3T0RNUGdnY1RIclQxWklocmFVSzUxb2xzNk82cG8tbmdiOE1TSGdYMHVTbDJEb0Q0cG1qTzVNZGRyU29pbEZJYUdGbFAzQTFYbWJ4bXN6NTZHYnlHUVgzdkt6S1VGSlJBTEF2Q0pwVWZNOGFKbEQ2V2ZEd1FHUTBSc0pQYk5EM2dVUlVZZEZPLXBaV2phLUNkb1kzcHFlR0tzNHBaTDVGY29N","email":"rnoushi@edc4it.com"}}}
sshKey: | 
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqwwQfGdhxHae+LMfx4o9cB/WictCznPkauXYqQC1UJNE6FmdZROCskqrCcj6LYgAgvz/w+kByP5O//JMXqE4uxWcxne70Mr5RIAka4WRO6/fJcWcYhkPMvrp3d1T9zKo+tdHSfxK86FKf2NWI4nFjYR/bQg+tMtHV9GtewJxc6nrSbTWH+zSBazJ3IdBMnlu8/2KwYPMtLFLVr4ZnmzLjRUeJqZ4AVQPcGgJwfKldFWt9uj40rKzCUsmU1WZh086CmxsUqEN7HaxalzKU4RP1vcIX6g/XxQS/C005wTBBnKPGE+FZ3oQEJxL6bqSSgjRI5SOhEyPT5KEcqBvZg3mWLmduxzd9HDv52hY0ZPK+wZkN/zmnYTjuvtY796cMBAXR6RCZVH39K+5x6ozamOyNMse6qpVhjKafL9c7S+knJlQCDaLJuAUA6aZhTNZURcQ/fQA7QzcnDSeRxw7N7do7D8voLnXdNKcQY9jgOzjqtKqSOeZSLf02KS6L4huQygwDjrCfCvV1jy0DHFtXFThMwwm+Tsxp5zMZZL9EP0ssRYNno4l7wsqJl3/MNtU/yFyg5Q7xJPwMBRa1O8VxWDJ8K1fuI5b3uaN5LHjrdCqOStCqKnhp+BG7DEqoWxngugsBUclsJ6L2PWTHSQhTYukPPu7wsisCkUA05aK36yKIbw== lab@utility.lab.example.com
imageContentSources:
  - mirrors:
    - nexus-registry-int.apps.tools-na.prod.nextcle.com/openshift/ocp4
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - nexus-registry-int.apps.tools-na.prod.nextcle.com/openshift/ocp4
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

    

