apiVersion: v1
data:
  install-config: |
    apiVersion: v1
    baseDomain: example.com
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform: {}
      replicas: 2
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform: {}
      replicas: 3
    imageContentSources:
    - mirrors:
      - nexus-registry-int.apps.tools-na.prod.nextcle.com/openshift/ocp4
      source: quay.io/openshift-release-dev/ocp-release
    - mirrors:
      - nexus-registry-int.apps.tools-na.prod.nextcle.com/openshift/ocp4
      source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    metadata:
      creationTimestamp: null
      name: ocp4
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      none: {}
    publish: External
    pullSecret: ""
    sshKey: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDqwwQfGdhxHae+LMfx4o9cB/WictCznPkauXYqQC1UJNE6FmdZROCskqrCcj6LYgAgvz/w+kByP5O//JMXqE4uxWcxne70Mr5RIAka4WRO6/fJcWcYhkPMvrp3d1T9zKo+tdHSfxK86FKf2NWI4nFjYR/bQg+tMtHV9GtewJxc6nrSbTWH+zSBazJ3IdBMnlu8/2KwYPMtLFLVr4ZnmzLjRUeJqZ4AVQPcGgJwfKldFWt9uj40rKzCUsmU1WZh086CmxsUqEN7HaxalzKU4RP1vcIX6g/XxQS/C005wTBBnKPGE+FZ3oQEJxL6bqSSgjRI5SOhEyPT5KEcqBvZg3mWLmduxzd9HDv52hY0ZPK+wZkN/zmnYTjuvtY796cMBAXR6RCZVH39K+5x6ozamOyNMse6qpVhjKafL9c7S+knJlQCDaLJuAUA6aZhTNZURcQ/fQA7QzcnDSeRxw7N7do7D8voLnXdNKcQY9jgOzjqtKqSOeZSLf02KS6L4huQygwDjrCfCvV1jy0DHFtXFThMwwm+Tsxp5zMZZL9EP0ssRYNno4l7wsqJl3/MNtU/yFyg5Q7xJPwMBRa1O8VxWDJ8K1fuI5b3uaN5LHjrdCqOStCqKnhp+BG7DEqoWxngugsBUclsJ6L2PWTHSQhTYukPPu7wsisCkUA05aK36yKIbw== lab@utility.lab.example.com
kind: ConfigMap
metadata:
  name: cluster-config-v1
  namespace: kube-system
