apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-metric-serving-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDJjCCAg6gAwIBAgIIfLJqyX2kykMwDQYJKoZIhvcNAQELBQAwMTESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRswGQYDVQQDExJldGNkLW1ldHJpYy1zaWduZXIwHhcNMjEw
    MjI2MTUyMzEzWhcNMzEwMjI0MTUyMzEzWjAxMRIwEAYDVQQLEwlvcGVuc2hpZnQx
    GzAZBgNVBAMTEmV0Y2QtbWV0cmljLXNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAKKlcQz965qiMm7OIYymx2QK6UvQwmBj9NFjTrvenrwUyA57
    gOJ22z8FPWH9IQ6ZEZgHPXYh1TwbZf4xgNpKLXhSZd4Xo7sa4O6fknacLFfEUrY0
    ZzVIzlNPrBxeaSXQDu+ZNDY80yyf7vQeitzxkCzAG5kXFFLsSrwNPKG7/QykchhC
    00mV3DtNe4pf9VQEa7L3U//ghYdQ1YiAmRR1xaQib29ELjZHVMYSeNsZlU852uPJ
    wE3hoeAvypwqxdmApuDyO74ypu4jCxSEkBI4Ux8cY1uF53Va6KZh4t1JrMqWxwAM
    LfV2nVuQdLFIzGVDav+SnV8MpvN7zGtnVQn0FhUCAwEAAaNCMEAwDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKkJ6gdA27rTTnXN3NBv
    RCWnXg88MA0GCSqGSIb3DQEBCwUAA4IBAQAUpdUkedd8vGPrz2QarVfc7DHdnGKH
    Fa1cGfbYmBMtMyUYNFabIqB6t0E2HlZUTuz2DSrr9CSK8Pius4IXKeAzQtjn/GXH
    OSWmYOo6kPU/yVBm1sgCRRq3alAruAPEPn+ugPaz9k0HKRpJjsMJ0UvziV7TDpfL
    re6IacL7YDyOSVlh68RkD+QRXatRN5OVbvRsp9P5UVWuK7oFhDnfN0l5LOgNx3Mh
    z0bzBJ9uGf+V5iPDPwqAweOc6Hwk2YZGi120kTASXojE0zjFRwRFE4qzPtBNdsRl
    4FyJl29+cf48/IlWGyroKFch4X3VCL0AlIn+nB+r0MpwqOTDyXmOR4qU
    -----END CERTIFICATE-----
    
